# @package _group_
  type: MultiView_canonical_dataset_blender
  args: 
    dataset_path: "../data/DRACO20K_cars/" # "../data/sunny_cars/"
    num_views: 3
    train: 1
    normalize: True
    gt_depth: False
    jitter: True
    canonical: True

  loader:
    args:
      batch_size: 2
      num_workers: 8
      shuffle: True

