# @package _group_
  type: MultiView_dataset_blender
  args: 
    dataset_path: "../prepared_data/chairs/"
    num_views: 3
    train: 1
    gt_depth: False

  loader:
    args:
      batch_size: 2
      num_workers: 4
      shuffle: True
