# @package _group_
  type: MultiView_dataset
  args: 
    dataset_path: "../prepared_data/cars-3/"
    num_views: 3
    train: 2
  loader:
    args:
      batch_size: 2
      num_workers: 4
      shuffle: True
